[package]
name = "ballbounce"
version = "0.2.0"
authors = ["RogeÌrio Sampaio de Almeida <rsalmei@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
